=== CodeAcademie/CodeAcademie.github.io/assets/programmePedago.dtd
<!ELEMENT root (Programme*) >
<!ELEMENT Programme (Module*) >

<!ATTLIST Programme formation CDATA #IMPLIED>
<!ELEMENT Module (Objectif, PreRequis, Materiel, Sequence*)>
<!ATTLIST Module language CDATA "">
<!ATTLIST Module group CDATA "">
<!ELEMENT Sequence (Objectif, Activite*)>
<!ATTLIST Sequence evaluation CDATA "">
<!ELEMENT Activite (Objectif, Code,Type, Temps?, SousObjectif?, Description?, Link?, Tag?)>
<!ATTLIST Activite done (true|false) "false">
<!ELEMENT Objectif (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT PreRequis (#PCDATA) >
<!ELEMENT Materiel (#PCDATA) >
<!ELEMENT SousObjectif (#PCDATA) >
<!ELEMENT Temps (#PCDATA) >
<!ELEMENT Code (#PCDATA) >
<!ELEMENT Type (#PCDATA) >
<!ELEMENT Link (#PCDATA) >
<!ELEMENT Tag (#PCDATA) >
<!ELEMENT Planning (Semaine*) >
<!ELEMENT Semaine (Jour*)>
<!ELEMENT Jour (Task*)>
<!ELEMENT Task (#PCDATA)>
<!ATTLIST Semaine number CDATA "0">
<!ATTLIST Jour ferie (true|false) "false">
<!ATTLIST Jour number CDATA "0">
<!ATTLIST Task time CDATA "7">

=== CodeAcademie/CodeAcademie.github.io/RN01/programme.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE root
  SYSTEM 'programmePedago.dtd'>
<root>
	<Programme formation="Referent Numerique">
		<Module group="Referent_Numerique" language="PHP">
			<Objectif>TODO</Objectif>
			<Sequence>
				<Objectif>TODO</Objectif>
				<Activite>
					<Objectif>Initiation Ã  la gestion de projet</Objectif>
					<Code>WEB-RN01-01</Code>
					<Description>
[OpenClassroom - Gestion Projet - 6h](https://openclassrooms.com/courses/decouvrez-les-bases-de-la-gestion-de-projet)
[OpenClassroom - Cahier des charges - 8h](https://openclassrooms.com/courses/realisez-le-cahier-des-charges-d-un-projet-digital)
					</Description>
				</Activite>
				<Activite>
					<Objectif>Mise en pratique de la gestion de projet</Objectif>
					<Code>WEB-RN01-02</Code>
					<Description>
						https://github.com/simplon-erwann-duclos/fork/blob/master/ChargeProjetNumerique.md
					</Description>
				</Activite>
			</Sequence>
		</Module>
	</Programme>
</root>

=== CodeAcademie/CodeAcademie.github.io/TC02/programme.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE root
  SYSTEM 'programmePedago.dtd'>
<root>
	<Programme formation="Tronc Commun">
		<Module group="Tronc_Commun" language="HTML_CSS">
			<Objectif>Concevoir une application en HTML et CSS</Objectif>
			<PreRequis>Pré requis : N/A </PreRequis>
			<Materiel>Un pc / apprenant + video proj + raspberry pi (</Materiel>
			<Sequence evaluation="Brainstorming">
				<Objectif>Reconnaître les forces et faiblesses des navigateurs internet</Objectif>
				<Activite>
					<Objectif>Lister les fonctionnalités des navigateurs internet</Objectif>
					<Code>BRAIN02</Code>
					<Description>Activité à réaliser en sous groupes de 2 personnes. Ces derniers devront, par le biais du navigateur de leur choix, inspecter une page.
						Par le biais de l'inspecteur, ils devront :
							- lister l'ensemble des bibliothèques JS liées
							- lister l'ensemble des fichiers CSS liés
							- lister l'ensemble de fonctionnalités disponibles par l'inspecteur</Description>
				</Activite>
			</Sequence>
			<Sequence>
				<Objectif>Prendre conscience de l'interet de séparer la structure du graphisme</Objectif>
				<Activite done="true">
					<Objectif>Rédaction d'un XSLT </Objectif>
					<Code>XML02</Code>
					<SousObjectif></SousObjectif>
					<Description>
						Manipulez le XSLT afin d'avoir un rendu HTML de votre XML. 
						Vous pouvez également utiliser le XSLT pour exporter vers un autre XML (ayant un autre DTD)! 
					</Description>
				</Activite>
			</Sequence>
			<Sequence>
				<Objectif>Développer un site web en HTML5</Objectif>
				
				<Activite done="true">
					<Objectif>Mise en pratique</Objectif>
					<Code>HTML05</Code>
					<SousObjectif>Prise de conscience de l'importance d'une spec détaillée avec le client</SousObjectif>
					<Description>Continuez les projets initiés lors de la prairie. Mêmes équipes mais scindés en deux sous groupes, voire 3 pour le groupe de 6.</Description>
				</Activite>
				<Activite done="true">
					<Objectif>Projet HTML</Objectif>
					<Code>HTML09</Code>
					<Description>
https://github.com/ErwannFace/Challenge_1
https://github.com/ErwannFace/Challenge_2
https://github.com/ErwannFace/Challenge_4
https://github.com/ErwannFace/Challenge_5
					</Description>
				</Activite>
				
			</Sequence>
			<Sequence>
				<Objectif>Initiation à l'accessibilité Web</Objectif>
				<Activite>
					<Objectif>Initiation à l'accessibilité Web</Objectif>
					<Code>WEB01</Code>
					<Description>
http://www.commentcamarche.net/contents/1255-ergonomie-d-un-site-web
http://simplonline.co/uploads/images/Front_End/zuliegarnier/Web_accessibility_fr.png
https://www.w3.org/WAI/References/QuickTips/qt-fr.htm
http://simplonline.co/ressources/ress-methodo/50-normes-accessibilite-w3c
					</Description>
				</Activite>
			</Sequence>
		</Module>
		<Module group="Tronc_Commun" language="JS">
			<Objectif>Concevoir une application web avec JavaScript</Objectif>
			<PreRequis>N/A </PreRequis>
			<Materiel>N/A </Materiel>
			<Sequence>
				<Objectif>Identifier les différentes fonctionnalités de JS</Objectif>
				<Activite>
					<Objectif>Identifier les différentes fonctionnalités de JS</Objectif>
					<Code>JS01</Code>
					<Description>
						
					</Description>
				</Activite>
			</Sequence>
			<Sequence>
				<Objectif>Programmer avec les fondamentaux du JavaScript</Objectif>
				<Activite>
					<Objectif>Programmer avec les fondamentaux du JavaScript</Objectif>
					<Code>JS10</Code>
					<Description>
https://openclassrooms.com/courses/dynamisez-vos-sites-web-avec-javascript/introduction-au-javascript

Exercices associés :
https://github.com/ErwannFace/JS_Exercice-01
https://github.com/ErwannFace/JS_Exercice-01-Bonus
http://www.grappa.univ-lille3.fr/~torre/Enseignement/TPs/JavaScript/
					</Description>
				</Activite>
				<Activite>
					<Objectif>Programmer en JavaScript</Objectif>
					<Code>JS11</Code>
					<Description>
https://github.com/ErwannFace/JS_Exercice-02
https://github.com/ErwannFace/JS_Exercice-03					
Video explicative : https://www.grafikart.fr/tutoriels/javascript/sommaire-dynamique-667
					</Description>
				</Activite>

			</Sequence>
			<Sequence>
				<Objectif>Mettre en œuvre la gestion d'événements  au sein de JavaScript</Objectif>
				<Activite>
					<Objectif>Projet Cookie clicker</Objectif>
					<Code>JS12</Code>
					<Description>
http://simplonline.co/ressources/19-defis/147-exercice-du-cookie-clicker
					</Description>
				</Activite>
				<Activite>
					<Objectif>Mettre en œuvre la gestion d'événements  au sein de JavaScript</Objectif>
					<Code>JS20</Code>
					<Description>
					</Description>

				</Activite>
			</Sequence>
		</Module>

		<Module group="Tronc_Commun" language="Gestion de Projet">
			<Objectif>Experimenter les différents rôles d'un chef de projet</Objectif>
			<PreRequis>N/A </PreRequis>
			<Materiel>N/A </Materiel>
			<Sequence>
				<Objectif>Communiquer avec un client</Objectif>
				<Activite>
					<Objectif>Code Combat</Objectif>
					<Code>COD01</Code>
					<Description>
						http://simplonline.co/ressources/ress-culturegeek/220-comment-expliquer-la-programmation-aux-enfants
					</Description>
				</Activite>
			</Sequence>
		</Module>
		<Module group="Tronc_Commun" language="Culture Générale">
			<Objectif>Identifier les éléments intrinsèques d'un développeur WEB</Objectif>
			<PreRequis>N/A </PreRequis>
			<Materiel>N/A </Materiel>
			<Sequence>
				<Objectif>Culture Générale sur l'informatique</Objectif>
				<Activite>
					<Objectif>Poses-toi une question</Objectif>
					<Code>CUL00</Code>
					<Description>Chaque semaine les apprenants définissent des thématiques à rechercher.
						Chaque semaine, un apprenant sélectionné au hasard présente son axe de recherche</Description>
					
				</Activite>
				
				<Activite>
					<Objectif>Le droit de l'informatique</Objectif>
					<Code>CUL04</Code>
					<Description>Brainstorming Intervention d'ange</Description>
				</Activite>
				<Activite>
					<Objectif>Compréhender le fonctionnement des serveurs </Objectif>
					<Code>CUL05</Code>
				</Activite>
				<Activite>
					<Objectif>Approfondir GIT </Objectif>
					<Code>GIT01</Code>
					<Description>
						1) Réaliser une gitpage
						2) Approfondir git avec https://github.com/git-tips/tips
						3) http://jnthn.net/training/git/exercises.pdf
						4) http://gitimmersion.com/
					</Description>
				</Activite>
			</Sequence>
		
			<Sequence>
				<Objectif>Initiation à l'algorithmie</Objectif>
				<Activite>
					<Objectif>Amusement park in Algobox</Objectif>
					<Code>ALGO01</Code>
					<Description>
						Sur Algobox : 
http://www.methodemaths.fr/exoalgo/#partiedecimale
					</Description>
				</Activite>
				<Activite>
					<Objectif>Pratiquer l'algorithmie</Objectif>
					<Code>ALGO02</Code>
					<Description>Avec uniquement un papier et un crayon, réaliser les algorithmes suivants : 
						- Plus Grand / Plus Petit
						- Convertir une heure du AM/PM format au format militaire sur 24h. Sachant que 12AM = 12h00 et 12PM = 0h00
						- Créer une fonction réalisant la somme de N chiffres
						- Créer une fonction trouvant le plus petit élément d'un tableau
					</Description>
				</Activite>
				<Activite>
					<Objectif>Approfondir l'algo avec le JS</Objectif>
					<Code>ALGOJS</Code>
					<Description>
https://github.com/simplonco/js-recall
					</Description>
				</Activite>
			</Sequence>
			<Sequence>
				<Objectif>Projets</Objectif>
				<Activite>
					<Objectif>Projet Profesionel</Objectif>
					<Code>PROJ</Code>
					<Description>Répondre à un cahier des charges d'un commanditaire.</Description>
				</Activite>
			</Sequence>
			<Sequence>
				<Objectif>Insertion Professionelle expliquée par Face</Objectif>
				<Activite>
					<Objectif>Insertion Profesionelle</Objectif>
					<Code>INS PRO</Code>
					<Description>Géré par Face</Description>
				</Activite>
			</Sequence>
		</Module>
	</Programme>
</root>

=== CodeAcademie/CodeAcademie.github.io/TC03/planning.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="31">
		<Jour number="1" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="2" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="3" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="4" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="5" ferie="true"><Task time="7">Work@Home</Task></Jour>
	</Semaine>
	<Semaine number="32">
		<Jour number="1" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="2" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="3" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="4" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="5" ferie="true"><Task time="7">Work@Home</Task></Jour>
	</Semaine>
	<Semaine number="33">
		<Jour number="1" ferie="true"><Task time="7">Work@Home</Task></Jour>
		<Jour number="2" ferie="true"><Task time="7">FERIE</Task></Jour>
		<Jour number="3">
			<Task time="1">CUL04</Task>
			<Task time="6">JS12</Task>
		</Jour>
		<Jour number="4">
			<Task time="6">WP99</Task>
			<Task time="1">CUL15</Task>
		</Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	<Semaine number="34">
		<Jour number="1" >
			<Task time="3">CERT01</Task></Jour>
			<Task time="4"></Task></Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6"></Task>
		</Jour>
		<Jour number="3">
			<Task time="2">CERT01</Task>
			<Task time="5"></Task>
		</Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	<Semaine number="35">
		<Jour number="1" ><Task time="7"></Task></Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6"></Task>
		</Jour>
		<Jour number="3"><Task time="7"></Task></Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	<!--Semaine number="28">
		<Jour number="1">
			<Task time="4">JS11</Task>
			<Task time="3">JS11</Task>
		</Jour>
		<Jour number="2">
			<Task time="4">JS11</Task>
			<Task time="2">Intervention Antoine et Tyjow</Task>
			<Task time="1">Intervention Annaelle</Task>
			
		</Jour>
		<Jour number="3">
			<Task time="3">PROJ</Task>
			<Task time="4">JS99</Task>
			
		</Jour>
		<Jour number="4" ferie="true"><Task time="7"></Task></Jour>
		<Jour number="5" ferie="true"><Task time="7"></Task></Jour>
	</Semaine>
	<Semaine number="29">
		<Jour number="1">
			<Task time="3">PROJ</Task>
			<Task time="3">JS11</Task>
			<Task time="1">CUL00</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">PROJ</Task>
			<Task time="3">JS11</Task>
			<Task time="1">Intervention Portage Salarial</Task>
		</Jour>
		<Jour number="3">
			<Task time="3">PROJ</Task>
			<Task time="1">POO01</Task>
			<Task time="2">JS20</Task>
			<Task time="1">JS99</Task>
		</Jour>
		<Jour number="4" ferie="true"> 
			<Task time="7">INS PRO</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">PROJ</Task>
			<Task time="4">JS21</Task>
		</Jour>
	</Semaine>
	<Semaine number="30">
		<Jour number="1">
			<Task time="3">JS21</Task>
			<Task time="4">PROJ</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">JS21</Task>
			<Task time="4">JS21</Task>
		</Jour>
		<Jour number="3">
			<Task time="6">JS21</Task>
			<Task time="1">JS99</Task>
		</Jour>
		<Jour number="4" ferie="true">
			<Task time="7">INS PRO</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">PROJ</Task>
			<Task time="2">PROJ</Task>
			<Task time="1">CUL00</Task>
			<Task time="1">PHP00</Task>	
		</Jour>
	</Semaine>
	<Semaine number="31">
		<Jour number="1">
			<Task time="3">PROJ</Task>
			<Task time="3">CMS01</Task>
			<Task time="1">GES01</Task>
		</Jour>
		<Jour number="2">
			<Task time="6">CMS01</Task>
			<Task time="1">CUL00</Task> juliette et abdul
		</Jour>
		<Jour number="3">
			<Task time="6">CMS01</Task>
			<Task time="1">CUL00</Task> ghaffar
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
			<Task time="6">CMS01</Task>
			<Task time="1">CUL00</Task>
		</Jour>
	</Semaine-->
</Planning>

=== CodeAcademie/CodeAcademie.github.io/Prairie/planning.xml
<?xml version ="1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="21">
		<Jour number="1">
			<Task time="1">SOC01</Task>
			<Task time="1">SOC03</Task>

			<Task time="1">FACE00</Task>
			<Task time="4">LIN02b</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">DEV00</Task>
			<Task time="4">HTML00</Task>
			<Task time="2">JS00</Task>
		</Jour>

		<Jour number="3">
			<Task time="5">PHP00</Task>
			<Task time="2">HTML99</Task>
			
		</Jour>
		<Jour number="4" ferie="true">
			<Task time="7">FERIE</Task>
		</Jour>
		<Jour number="5" ferie="true">
			<Task time="7">FERIE</Task>
		</Jour>
	</Semaine>
	<Semaine number="22">
		<Jour number="1">
			<Task time="2">HTML01</Task>
			<Task time="5">GIT00</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">RUB00</Task>
			<Task time="1">DEV02</Task>
			<Task time="3">SQL00</Task>
		</Jour>

		<Jour number="3">
			<Task time="4">CSS00</Task>
			<Task time="3">JS01</Task>
		</Jour>
		<Jour number="4">
			<Task time="6">WP00</Task>
			<Task time="1">DEV03</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine>

</Planning>

=== CodeAcademie/CodeAcademie.github.io/TC05/planning.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="39">
		<Jour number="1">
			<Task time="7">WEB-PHP-06</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">WEB-PHP-06</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">GES-04-01</Task>
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
				<Task time="7">GES-04-01</Task>
		</Jour>
	</Semaine>
	<Semaine number="40">
		<Jour number="1">
			<Task time="7">WEB-PHP-07</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">WEB-PHP-07</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">WEB-PHP-07</Task>
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
			<Task time="7">WEB-PHP-07</Task>
		</Jour>
	</Semaine>

</Planning>

=== CodeAcademie/CodeAcademie.github.io/Fork/wp.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="41">
		<Jour number="1" >
			<Task time="7"> </Task>
		</Jour>
		<Jour number="2">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="7"></Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="42">
		<Jour number="1" >
			<Task time="7"></Task>
		</Jour>
		<Jour number="2">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="4"> </Task>
			<Task time="3"> </Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Intervention : Gwenn Houedry</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="43">
		<Jour number="1" >
			<Task time="7"> </Task>
		</Jour>
		<Jour number="2">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">OPQUAST</Task>
		</Jour>
		<Jour number="4">
			<Task time="7"></Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Intervention : Djafar</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
</Planning>

=== CodeAcademie/CodeAcademie.github.io/TC01/planning.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<?xml-stylesheet href="styleProgrammePedago.css" type="text/css" ?>
<Planning >
	<Semaine number="23">
		<Jour number="1" ferie="true"><Task time="7">Feri√©</Task></Jour>
		<Jour number="2">
			<Task time="1">SOC05</Task>
			<Task time="1">SOC04</Task>
			<Task time="2">SOC03</Task>
			<Task time="1">SOC06</Task>
			<Task time="1">SOC07</Task>
			<Task time="1">CUL00</Task>
		</Jour>
		<Jour number="3">
			<Task time="4">SCRUM01</Task>
			<Task time="3"></Task>
		</Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	<Semaine number="24">
		<Jour number="1" ><Task time="7"></Task></Jour>
		<Jour number="2">
			<Task time="1">CUL02</Task>
		</Jour>
		<Jour number="3"><Task time="7"></Task></Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	<Semaine number="25">
		<Jour number="1" ><Task time="7"></Task></Jour>
		<Jour number="2">
			<Task time="1">CUL03</Task>
		</Jour>
		<Jour number="3"><Task time="7"></Task></Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	<Semaine number="26">
		<Jour number="1" ><Task time="7"></Task></Jour>
		<Jour number="2"><Task time="7"></Task></Jour>
		<Jour number="3"><Task time="7"></Task></Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5"><Task time="7">INS PRO</Task></Jour>
	</Semaine>
	
</Planning>

=== CodeAcademie/CodeAcademie.github.io/FE01/programme.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE root
  SYSTEM 'programmePedago.dtd'>
<root>
	<Programme formation="Front End">
		<Module group="Front_End" language="PHP">
			<Objectif>Développer dans des langages web</Objectif>
			<Sequence>
				<Objectif>Développer un site web via AngularJS</Objectif>
				<Activite>
					<Objectif>Initiation à AngularJS</Objectif>
					<Code>WEB-FE-AngularJS-01</Code>
					<Description>

[Open Classroom - POO - 20h](https://openclassrooms.com/courses/apprenez-a-coder-avec-javascript/creez-vos-premiers-objets)
[Grafikart - POO - 25min](https://www.grafikart.fr/tutoriels/javascript/poo-javascript-object-466)
 
[Open Classroom - 10h](https://openclassrooms.com/courses/developpez-vos-applications-web-avec-angularjs)
[grafikart- 3h26 de videos](https://www.grafikart.fr/formations/angularjs)
Simplonline - 1e semaine](http://simplonline.co/les-parcours/game-of-codes/207-semaine-12-game-of-codes)
[Simplonline - 2e semaine](http://simplonline.co/les-parcours/game-of-codes/249-semaine-13-game-of-codes)
[Lauterry - ?](http://lauterry.github.io/slides-handson-angular)

					</Description>
				</Activite>
				<Activite>
					<Objectif>Mise en pratique de AngularJS</Objectif>
					<Code>WEB-FE-AngularJS-02</Code>
					<Description>
						https://github.com/simplon-erwann-duclos/fork/blob/master/FrontEnd.md
					</Description>
				</Activite>
			</Sequence>
		</Module>
		<Module>
			<Objectif>Pratiquer avec aisance l'algorithmie</Objectif>
			<Sequence>
				<Objectif>Approfondir l'algorithmie</Objectif>
				<Activite>
					<Objectif>Approfondir l'algorithmie sur Coding Game</Objectif>
					<Code>WEB-COD-01</Code>
					<Description>
						En pair programming, réalisez un exercice de coding game. En utilisant le language JavaScript.
					</Description>
				</Activite>
			</Sequence>
		</Module>
	</Programme>
</root>
