=== CodeAcademie/CodeAcademie.github.io/assets/programmePedago.dtd
<!ELEMENT root (Programme*) >
<!ELEMENT Programme (Module*) >

<!ATTLIST Programme formation CDATA #IMPLIED>
<!ELEMENT Module (Objectif, PreRequis, Materiel, Sequence*)>
<!ATTLIST Module language CDATA "">
<!ATTLIST Module group CDATA "">
<!ELEMENT Sequence (Objectif, Activite*)>
<!ATTLIST Sequence evaluation CDATA "">
<!ELEMENT Activite (Objectif, Code,Type, Temps?, SousObjectif?, Description?, Link?, Tag?)>
<!ATTLIST Activite done (true|false) "false">
<!ELEMENT Objectif (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT PreRequis (#PCDATA) >
<!ELEMENT Materiel (#PCDATA) >
<!ELEMENT SousObjectif (#PCDATA) >
<!ELEMENT Temps (#PCDATA) >
<!ELEMENT Code (#PCDATA) >
<!ELEMENT Type (#PCDATA) >
<!ELEMENT Link (#PCDATA) >
<!ELEMENT Tag (#PCDATA) >
<!ELEMENT Planning (Semaine*) >
<!ELEMENT Semaine (Jour*)>
<!ELEMENT Jour (Task*)>
<!ELEMENT Task (#PCDATA)>
<!ATTLIST Semaine number CDATA "0">
<!ATTLIST Jour ferie (true|false) "false">
<!ATTLIST Jour number CDATA "0">
<!ATTLIST Task time CDATA "7">

=== CodeAcademie/CodeAcademie.github.io/RN01/planning.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="41">
		<Jour number="1">
			<Task time="7">WEB-FE-AngularJS-01</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">WEB-FE-AngularJS-02</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">WEB-FE-AngularJS-02</Task>
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
			<Task time="7">WEB-FE-AngularJS-02</Task>
		</Jour>
	</Semaine>
</Planning>

=== CodeAcademie/CodeAcademie.github.io/ORGA/Next.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM '../programmePedago.dtd'>
<?xml-stylesheet href="../css/style.css" type="text/css" ?>
<Planning >
	
	
	<Semaine number="48">
		<Jour number="1"><Task time="7">OPQUAST </Task></Jour>
		<Jour number="2"><Task time="7">FORK </Task></Jour>
		<Jour number="3"><Task time="7">FORK </Task></Jour>
		<Jour number="4">
			<Task time="1">SPRINT#02 </Task>
			<Task time="6">FORK </Task>
		</Jour>
		<Jour number="5"><Task time="7">INS PRO </Task></Jour>
	</Semaine>
	<Semaine number="49">
		<Jour number="1"><Task time="7">TDD03 </Task></Jour>
		<Jour number="2"><Task time="7">TDD03 </Task></Jour>
		<Jour number="3"><Task time="7">CA20 </Task></Jour>
		<Jour number="4"><Task time="7">CA20 </Task></Jour>
		<Jour number="5"><Task time="7">CapGemini - Secure Coding </Task></Jour>
	</Semaine>

	<Semaine number="50">
		<Jour number="1"><Task time="7">FORK </Task></Jour>
		<Jour number="2"><Task time="7">FORK </Task></Jour>
		<Jour number="3"><Task time="1">SPRINT#03 </Task>
			<Task time="6">FORK </Task></Jour>
		<Jour number="4"><Task time="7">CERT05 </Task></Jour>
		<Jour number="5">
				<Task time="3">INS PRO</Task>
				<Task time="4">French Tech</Task>
		</Jour>
	</Semaine>
	<Semaine number="51">
		<Jour number="1"><Task time="3">Visite CapGemini</Task><Task time="4">CA20</Task></Jour>
		<Jour number="2"><Task time="7">CA20</Task></Jour>
		<Jour number="3"><Task time="7">CA20</Task></Jour>
		<Jour number="4"><Task time="7">Certif OPQUAST</Task></Jour>
		<Jour number="5"><Task time="7">INS PRO </Task></Jour>
	</Semaine>
	<Semaine number="52">
		<Jour number="1" ferie="true">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="2" ferie="true">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="3" ferie="true">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="4" ferie="true">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="5" ferie="true">
			<Task time="7"></Task>
		</Jour>
	</Semaine>
	<Semaine number="1">
		<Jour number="1" ferie="true">
			<Task time="7"> </Task>
		</Jour>
		<Jour number="2">
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="3">
			<Task time="1">SPRINT#04 </Task>
			<Task time="6">CA20 </Task>
		</Jour>
		<Jour number="4">
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO </Task>
		</Jour>
	</Semaine>
	<Semaine number="2">
		<Jour number="1">
			<Task time="7">CA20 </Task>
		</Jour>
		<Jour number="2">
			<Task time="7">CA40 </Task>
		</Jour>
		<Jour number="3">
			<Task time="7">SimulationEntretien </Task>
		</Jour>
		<Jour number="4">
			<Task time="7">CA20 </Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO </Task>
		</Jour>
	</Semaine>
	<Semaine number="3">
		<Jour number="1">
			<Task time="7">PREPA CERTIF</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">CERTIF</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">CERTIF</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">INS PRO</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">SimulationEntretien</Task>
		</Jour>
	</Semaine>
	<Semaine number="4">
		<Jour number="1">
			<Task time="7">INS PRO</Task>
		</Jour>
		<Jour number="2" ferie="true">
			<Task time="7"></Task>
		</Jour>
		<Jour number="3" ferie="true">
			<Task time="7"></Task>
		</Jour>
		<Jour number="4" ferie="true">
			<Task time="7"></Task>
		</Jour>
		<Jour number="5" ferie="true">
			<Task time="7"></Task>
		</Jour>
	</Semaine>
</Planning>

=== CodeAcademie/CodeAcademie.github.io/TC02/planning.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="27">
		<Jour number="1" >
			<Task time="7">PHP11</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="1">PHP99</Task>
			<Task time="5">WP99</Task>
		</Jour>
		<Jour number="3">
			<Task time="6">ALGO</Task>
			<Task time="1">PHP99</Task>
		</Jour>
		<Jour number="4">
			<Task time="4">HTML04</Task>
			<Task time="3">LIBRE </Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Intervention HTMY</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="28">
		<Jour number="1" ferie="true">
			<Task time="7">Work@Home</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6">CA00</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">WP99</Task>
		</Jour>
		<Jour number="4"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5" ferie='true'><Task time="7">FERIE</Task></Jour>
	</Semaine>
	<Semaine number="29">
		<Jour number="1" >
			<Task time="1">CUL12</Task>
			<Task time="4">ALGO</Task>
			<Task time="2">PHP11</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6">WP99</Task>
			
		</Jour>
		<Jour number="3">
			<Task time="1">CUL13</Task>
			<Task time="3">PHP11</Task>
			<Task time="3">JS10</Task>
		</Jour>
		<Jour number="4">
			<Task time="1">CUL10</Task>
			<Task time="1">CUL11</Task>
			<Task time="5">WP99</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">Intervention DOLMEN</Task>
			<Task time="4">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="30">
		<Jour number="1" ><Task time="7"></Task></Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6"></Task>
		</Jour>
		<Jour number="3"><Task time="7"></Task></Jour>
		<Jour number="4"><Task time="7"></Task></Jour>
		<Jour number="5">
			<Task time="3">Intervention Big Me Up</Task>
			<Task time="4">INS PRO</Task>
		</Jour>
	</Semaine>
</Planning>

=== CodeAcademie/CodeAcademie.github.io/Fork/integ.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<!-- Semaine number="41">
		<Jour number="1" >
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6">CA20</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">MAINTENANT</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="42">
		<Jour number="1" >
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">CSS15</Task>
		</Jour>
		<Jour number="3">
			<Task time="3">GB01</Task>
       		<Task time="4">CSS15</Task>
		</Jour>
		<Jour number="4">
			<Task time="4">CSS15</Task>
			<Task time="3">CERT01</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Gwenn Houedry</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="43">
		<Jour number="1" >
			<Task time="3">SQL20</Task>
			<Task time="4">SQL30</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">SQL20</Task>
			<Task time="4">SQL30</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">OPQUAST</Task>
		</Jour>
		<Jour number="4">
			<Task time="4">CA20</Task>
			<Task time="3">CERT03</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Christophe DJAFAR</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="44">
		<Jour number="1" >
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">INS PRO</Task>
		</Jour>
		<Jour number="3" ferie="true">
       		<Task time="7"> </Task>
		</Jour>
		<Jour number="4">
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">CA20</Task>
		</Jour>
	</Semaine >
	<Semaine number="45">
		<Jour number="1" >
			<Task time="7">CSS15</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">CSS15</Task>
		</Jour>
		<Jour number="3">
       		<Task time="7">CSS15</Task>
		</Jour>
		<Jour number="4">
			<Task time="3">CERT04</Task>
			<Task time="4">CODING DOJO</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="46">
		<Jour number="1" >
			<Task time="7">TDD01</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">GB01</Task>
			<Task time="4">TDD01</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
			<Task time="4">TDD01</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">LIBRE</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine-->
	<Semaine number="47">
		<Jour number="1" >
			<Task time="3">GB01</Task>
			<Task time="2">Village By CA</Task>
			<Task time="2">TDD01</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">TDD02</Task>
			<Task time="4">CODING DOJO</Task>
		</Jour>
		<Jour number="3">
       		<Task time="1">BDD02</Task>
			<Task time="6">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Laurent SELLIN</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="48">
		<Jour number="1"><Task time="7">OPQUAST</Task></Jour>
		<Jour number="2"><Task time="5">INTEG</Task><Task time="2">INSPRO51</Task></Jour>
		<Jour number="3"><Task time="7">INTEG</Task></Jour>
		<Jour number="4"><Task time="7">CERT04.1</Task></Jour>
		<Jour number="5">
			<Task time="3">INS PRO </Task>
			<Task time="1">EUDES ELIE </Task>
			<Task time="3">INS PRO </Task>
		</Jour>
	</Semaine>
	<Semaine number="49">
		<Jour number="1"><Task time="7">Coding DOJO Angular</Task></Jour>
		<Jour number="2">
			<Task time="7">Angular</Task>
		</Jour>
		<Jour number="3"><Task time="7">CA20</Task></Jour>
		<Jour number="4"><Task time="7">CA20</Task></Jour>
		<Jour number="5">
			<Task time="7">CapGemini - Secure Coding</Task>
		</Jour>
	</Semaine>
</Planning>

=== CodeAcademie/CodeAcademie.github.io/TC05/programme.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE root
  SYSTEM 'programmePedago.dtd'>
<root>
	<Programme formation="Tronc Commun">
		<Module group="Tronc_Commun" language="PHP">
			<Objectif>Développer dans des langages web</Objectif>
			<Sequence>
				<Objectif>Développer un site web en PHP</Objectif>
				<Activite>
					<Objectif>Le Projet PHP</Objectif>
					<Code>WEB-PHP-06</Code>
					<Description>
						https://github.com/ErwannFace/php_projet
					</Description>
				</Activite>
				<Activite>
					<Objectif>Simplonsmus</Objectif>
					<Code>WEB-PHP-07</Code>
					<Description>
						Dans le cadre de simplonsmus, les apprenants vont réaliser des projets ensemble. 
						1) Le site de la promo
						2) Le site du hackathon
						3) Le site de bowling
						4) Une analyse du besoin d'ASRAC
						https://github.com/ErwannFace/projects
					</Description>
				</Activite>
			</Sequence>
		</Module>
		<Module group="Tronc_Commun" language="N/A">
			<Objectif>Compréhender les besoins nécessaires pour un chef de projet</Objectif>
			<Sequence>
				<Objectif>Travailler pour un client</Objectif>
				<Activite>
					<Objectif>Projet Profesionel</Objectif>
					<Code>GES-04-01</Code>
					<Description>
						Des vrais clients réalisent une demande à FACE pour implémenter leurs sites web. 
					</Description>
				</Activite>
			</Sequence>
		</Module>
	</Programme>
</root>

=== CodeAcademie/CodeAcademie.github.io/TC04/programme.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE root
  SYSTEM 'programmePedago.dtd'>
<root>
	<Programme formation="Tronc Commun">
		<Module group="Tronc_Commun" language="N/A">
			<Objectif>Avoir la culture générale d'un developpeur web junior</Objectif>
			<Sequence>
				<Objectif>Devenir curieux sur des technologies</Objectif>
				<Activite>
					<Objectif>Poses-toi une question</Objectif>
					<Code>CUL-01-01</Code>
					<Description>Chaque semaine les apprenants définissent des thématiques à rechercher.
						Chaque semaine, un apprenant sélectionné au hasard présente son axe de recherche</Description>
					
				</Activite>
				<Activite>
					<Objectif>Découverte d'une techno de son choix</Objectif>
					<Code>CUL-01-02</Code>
					<Description>
						Pendant les vacances, choisissez un framework ou une bibliothèque. Si vous manquez d'inspiration, recherchez des offres d'emploi. Puis lisez la documentation associée , et réalisez un premier projet. Lors de votre retour en classe, vous devrez être capable d'en parler , et d'expliquer à quoi elle sert et comment on peut l'utiliser.
					</Description>
				</Activite>
			</Sequence>
			<Sequence>
					<Objectif>Connaître le droit à l'informatique</Objectif>
					<Code>CUL-04</Code>
					<Activite>
						<Objectif>Connaitre le BA.B.A sur les différentes licences</Objectif>
						<Code>CUL-04-02</Code>
						<Description>
							Exercice sur les licences GPL, Creative Commons, MPL, Apache, MIT.
						</Description>
					</Activite>
			</Sequence>
			<Sequence>
					<Objectif>Savoir ce qu'est l'UI/UX</Objectif>
					<Code>CUL-05</Code>
					<Activite>
						<Objectif>Lecture d'un article sur l'ergonomie d'un site web</Objectif>
						<Code>CUL-05-02</Code>
						<Description>
							http://www.commentcamarche.net/contents/1255-ergonomie-d-un-site-web
						</Description>
					</Activite>
			</Sequence>
			<Sequence>
					<Objectif>Connaitre les principes de l'accessibilité web</Objectif>
					<Code>CUL-06</Code>
					<Activite>
						<Objectif>Lecture des règles WCAG 2.0</Objectif>
						<Code>CUL-06-01</Code>
						<Description>
							http://simplonline.co/uploads/images/Front_End/zuliegarnier/Web_accessibility_fr.png 
							https://www.w3.org/WAI/References/QuickTips/qt-fr.htm 
							https://www.w3.org/WAI/WCAG20/quickref/
						</Description>
					</Activite>
			</Sequence>
		</Module>
		<Module group="Tronc_Commun" language="PHP">
			<Objectif>Développer dans des langages web</Objectif>
			<Sequence>
				<Objectif>Développer un site web en PHP</Objectif>
				<Activite>
					<Objectif>Hello World</Objectif>
					<Code>WEB-PHP-01</Code>
					<Description>
						https://github.com/ErwannFace/php_hello_world
					</Description>
				</Activite>
				<Activite>
					<Objectif>Introduction au PHP</Objectif>
					<Code>WEB-PHP-02</Code>
					<Description>
						https://github.com/ErwannFace/php_introduction
					</Description>
				</Activite>
				<Activite>
					<Objectif>Lire et parcourir des données en PHP</Objectif>
					<Code>WEB-PHP-03</Code>
					<Description>
						https://github.com/ErwannFace/php_cooking_data
					</Description>
				</Activite>
				<Activite>
					<Objectif>Activité Pair programming : Les algorithmes de tri</Objectif>
					<Code>WEB-PHP-04</Code>
					<Description>
						https://github.com/ErwannFace/php_algo_tri
					</Description>
				</Activite>
				<Activite>
					<Objectif>Challenge du Mercredi</Objectif>
					<Code>WEB-PHP-05</Code>
					<Description>
						
					</Description>
				</Activite>
				<Activite>
					<Objectif>Le Projet PHP</Objectif>
					<Code>WEB-PHP-06</Code>
					<Description>
						
					</Description>
				</Activite>
			</Sequence>
		</Module>
		<Module group="Tronc_Commun" language="N/A">
			<Objectif>Compréhender les besoins nécessaires pour un chef de projet</Objectif>
			<Sequence>
				<Objectif>Travailler pour un client</Objectif>
				<Activite>
					<Objectif>Projet Profesionel</Objectif>
					<Code>GES-04-01</Code>
					<Description>
						Des vrais clients réalisent une demande à FACE pour implémenter leurs sites web. 
					</Description>
				</Activite>
			</Sequence>
		</Module>
		<Module group="Tronc_Commun" language="N/A">
			<Objectif> Accepter et s'intégrer au sein du groupe</Objectif>
			<Sequence>
				<Objectif>Définir le groupe</Objectif>
				<Activite>
					<Objectif>Election d'un délégué</Objectif>
					<Code>SOC10-02</Code>
					<Description>
						Plusieurs personnes peuvent se présenter pour les élections. S'il s'agit des premières élections, personne ne se connait. Le vote final peut se réaliser au shifumi
					</Description>
				</Activite>
			</Sequence>
		</Module>
		
	</Programme>
</root>

=== CodeAcademie/CodeAcademie.github.io/TC04/planning.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<Semaine number="34">
		<Jour number="1">
			<Task time="2">CUL-01-02</Task>
			<Task time="2">WEB-PHP-01</Task>
			<Task time="3">WEB-PHP-02</Task>
		</Jour>
		<Jour number="2">
			<Task time="4">WEB-PHP-02</Task>
			<Task time="3">GES-04-01</Task>
		</Jour>
		<Jour number="3">
			
			<Task time="2">WEB-PHP-02</Task>
			<Task time="4">WEB-PHP-05</Task>
			<Task time="1">CUL-01-02</Task>
		</Jour>
		<Jour number="4">
			<Task time="2">CUL-01-02</Task>
			<Task time="3">WEB-PHP-02</Task>
			<Task time="2">GES-04-01</Task>
		</Jour>
		<Jour number="5">
			<Task time="5">WEB-PHP-04</Task>
			<Task time="1">CUL-01-02</Task>
			<Task time="1">CUL-01-01</Task> <!-- laty, hassan, floryan, nabil -->
		</Jour>
	</Semaine>
	<Semaine number="35">
		<Jour number="1">
			<Task time="6">WEB-PHP-02</Task>
			<Task time="1">CUL-01-02</Task>
		</Jour>
		<Jour number="2">
			<Task time="6">WEB-PHP-02</Task>
			<Task time="1">CUL-01-02</Task>
		</Jour>
		<Jour number="3">
			<Task time="6">GES-04-01</Task>
			<Task time="1">WEB-PHP-05</Task>
			
		</Jour>
		<Jour number="4" ferie="true">
			<Task time="1">CUL-01-02</Task>
			<Task time="6">INS PRO</Task>
		</Jour>
		<Jour number="5">
			<Task time="6">GES-04-01</Task>
			<Task time="1">SOC10-02</Task>
		</Jour>
	</Semaine>
	<Semaine number="36">
		<Jour number="1">
			<Task time="6">WEB-PHP-03</Task>
			<Task time="1">CUL-04-02</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">CUL-05-02</Task>
			<Task time="6">WEB-PHP-03</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">GES-04-01</Task>
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
			<Task time="7">GES-04-01</Task>
		</Jour>
	</Semaine>
	<Semaine number="37">
		<Jour number="1">
			<Task time="7">WEB-PHP-06</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">WEB-PHP-06</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">GES-04-01</Task>
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
				<Task time="7">GES-04-01</Task>
		</Jour>
	</Semaine>
	<Semaine number="38">
		<Jour number="1">
			<Task time="7">WEB-PHP-06</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">WEB-PHP-06</Task>
		</Jour>
		<Jour number="3">
			<Task time="7">GES-04-01</Task>
		</Jour>
		<Jour number="4" ferie="true"><Task time="7">INS PRO</Task></Jour>
		<Jour number="5">
				<Task time="7">GES-04-01</Task>
		</Jour>
	</Semaine>
</Planning>

=== CodeAcademie/CodeAcademie.github.io/Fork/mobile.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<!DOCTYPE Planning  SYSTEM 'programmePedago.dtd'>
<Planning >
	<!-- Semaine number="41">
		<Jour number="1" >
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="2">
			<Task time="1">VEIL01</Task>
			<Task time="6">CA20</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">MAINTENANT</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="42">
		<Jour number="1" >
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">RN10</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">RN10</Task>
		</Jour>
		<Jour number="4">
			<Task time="4">RN10</Task>
			<Task time="3">CERT01</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Gwenn Houedry</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="43">
		<Jour number="1" >
			<Task time="3">SQL20</Task>
			<Task time="4">SQL30</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">SQL20</Task>
			<Task time="4">SQL30</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
       		<Task time="4">OPQUAST</Task>
		</Jour>
		<Jour number="4">
			<Task time="4">CA20</Task>
			<Task time="3">CERT03</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Christophe DJAFAR</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="44">
		<Jour number="1" >
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">INS PRO</Task>
		</Jour>
		<Jour number="3" ferie="true">
       		<Task time="7"> </Task>
		</Jour>
		<Jour number="4">
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">CA20</Task>
		</Jour>
	</Semaine>
	<Semaine number="45">
		<Jour number="1" >
			<Task time="7">RN10</Task>
		</Jour>
		<Jour number="2">
			<Task time="7">RN10</Task>
		</Jour>
		<Jour number="3">
       		<Task time="7">RN10</Task>
		</Jour>
		<Jour number="4">
			<Task time="3">CERT04</Task>
			<Task time="4">CODINGDOJO</Task>
		</Jour>
		</Jour>
		<Jour number="5">
			<Task time="7">Mathieu KERJOUAN</Task>
		</Jour>
	</Semaine>
	<Semaine number="46">
		<Jour number="1" >
			<Task time="7">TDD01</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">GB01</Task>
			<Task time="4">TDD01</Task>
		</Jour>
		<Jour number="3">
       		<Task time="3">GB01</Task>
			<Task time="4">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">LIBRE</Task>
		</Jour>
		<Jour number="5">
			<Task time="7">INS PRO</Task>
		</Jour>
	</Semaine -->
	<Semaine number="47">
		<Jour number="1" >
			<Task time="3">GB01</Task>
			<Task time="2">Village By CA</Task>
			<Task time="2">TDD01</Task>
		</Jour>
		<Jour number="2">
			<Task time="3">TDD01</Task>
			<Task time="4">CODING DOJO</Task>
		</Jour>
		<Jour number="3">
       		<Task time="1">BDD02</Task>
			<Task time="6">CA20</Task>
		</Jour>
		<Jour number="4">
			<Task time="7">CA20</Task>
		</Jour>
		<Jour number="5">
			<Task time="3">INS PRO</Task>
			<Task time="1">Laurent SELLIN</Task>
			<Task time="3">INS PRO</Task>
		</Jour>
	</Semaine>
	<Semaine number="48">
		<Jour number="1"><Task time="7"> </Task></Jour>
		<Jour number="2"><Task time="7"> </Task></Jour>
		<Jour number="3"><Task time="7"> </Task></Jour>
		<Jour number="4"><Task time="7">CERT04.1</Task></Jour>
		<Jour number="5">
			<Task time="3">INS PRO </Task>
			<Task time="1">EUDES ELIE </Task>
			<Task time="3">INS PRO </Task>
		</Jour>
	</Semaine>
</Planning>
